name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE REQUEST] "
labels: [ feature request ]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Request
      description: Please describe the feature you would like to see added to the pack
      placeholder: Tell us what you want to see!
    validations:
      required: true
