JEIEvents.addItems(event => {
    event.add(Item.of('ae2:facade', '{item:"minecraft:stone"}'))
    event.add(Item.of('enderio:broken_spawner'))

    // Chests
    event.add(Item.of('sophisticatedstorage:chest', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:copper_chest', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:iron_chest', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:gold_chest', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:diamond_chest', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:netherite_chest', '{woodType:"oak"}'))
    // Barrels
    event.add(Item.of('sophisticatedstorage:barrel', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:copper_barrel', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:iron_barrel', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:gold_barrel', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:diamond_barrel', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:netherite_barrel', '{woodType:"oak"}'))
    // Limited Barrel 1
    event.add(Item.of('sophisticatedstorage:limited_barrel_1', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_copper_barrel_1', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_iron_barrel_1', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_gold_barrel_1', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_diamond_barrel_1', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_netherite_barrel_1', '{woodType:"oak"}'))
    // Limited Barrel 2
    event.add(Item.of('sophisticatedstorage:limited_barrel_2', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_copper_barrel_2', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_iron_barrel_2', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_gold_barrel_2', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_diamond_barrel_2', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_netherite_barrel_2', '{woodType:"oak"}'))
    // Limited Barrel 3
    event.add(Item.of('sophisticatedstorage:limited_barrel_3', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_copper_barrel_3', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_iron_barrel_3', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_gold_barrel_3', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_diamond_barrel_3', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_netherite_barrel_3', '{woodType:"oak"}'))
    // Limited Barrel 4
    event.add(Item.of('sophisticatedstorage:limited_barrel_4', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_copper_barrel_4', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_iron_barrel_4', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_gold_barrel_4', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_diamond_barrel_4', '{woodType:"oak"}'))
    event.add(Item.of('sophisticatedstorage:limited_netherite_barrel_4', '{woodType:"oak"}'))
    // Shulker Boxes
    event.add(Item.of('sophisticatedstorage:shulker_box'))
    event.add(Item.of('sophisticatedstorage:copper_shulker_box'))
    event.add(Item.of('sophisticatedstorage:iron_shulker_box'))
    event.add(Item.of('sophisticatedstorage:gold_shulker_box'))
    event.add(Item.of('sophisticatedstorage:diamond_shulker_box'))
    event.add(Item.of('sophisticatedstorage:netherite_shulker_box'))
})